### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BracerKirk** [JaouherK/streamDeck-weatherPlugin#21]
correct weather, then cycles between other weather after a few seconds.  query in stream deck for city is 'q=s11' as if I use 'Sheffield' it picks up the wrong city (Sheffield in Cornwall, not Sheffield in South Yorkshire which is what I want).  If I press the stream deck button again, it shows the correct temp for a few seconds again.

**Comment by JaouherK** [comment]
Dear @BracerKirk ,
Thanks for reporting this bug 👍 
It is possible when using WeatherAPi instead of OpenAPI to define which city by comma-separated position.
![image](https://user-images.githubusercontent.com/20973209/149006537-cbbeff41-b0d4-43f7-9f9d-fc2727f68672.png)
In fact as you can see in this picture when you sent the request the resolution of the place worked perfectly 
![image](https://user-images.githubusercontent.com/20973209/149006649-16d75ca7-362a-44f2-b8e4-acbb092c50ec.png)
Please update your settings accordingly :)
