### ISSUE TITLE
Area Code / City Name is now showing with no way to turn off....

### ISSUE THREAD

**Issue by krabs-github** [JaouherK/streamDeck-weatherPlugin#4]
Area Code / City Name is now showing with no way to turn off. This prevents showing the temp on the top. Some of the condition icons make the temp hard to read if it is on the bottom. The ability to switch the city label off, would be awesome.  It is also right justified and the temp is center justified. 

Thank you for this plug in and your time. 
![Screenshot 2021-05-20 121253](https://user-images.githubusercontent.com/78506543/119013175-bf29fc00-b964-11eb-897f-7fb9397a8f11.png)

**Comment by JaouherK** [comment]
@krabs-github Thank you for reaching out with this report  and for encouragements😃 
We are putting the city/area code as right-justified because the majority of icons are higher to the left 😞 
We can set of course a drop-down to display/hide the city name. However, would it be better to keep it at the top if we are able to avoid letting the weather icon affect the display of the temperature at the button?

**Comment by Pade2204** [comment]
I was about to report this "bug". I would really like to just turn city name off. Thanks

**Comment by JaouherK** [comment]
@Pade2204 Working on it 👍
It will be released on the next version

**Comment by Pade2204** [comment]
> @Pade2204 Working on it 👍
> It will be released on the next version
Thanks - I like the app though. Keep it up :)

**Comment by JaouherK** [comment]
Fix implemented, waiting for Elgato to deploy the new version. 👍 
Thank you @krabs-github  & @Pade2204 for contributing to making the plugin better
If you enjoyed the plugin please star the repository here
